export const colors = {
    light: {
        primary: {
            bg: 'bg-blue-600',
            text: 'text-white',
            textOutline: 'text-blue-600',
            hoverBg: 'hover:bg-blue-700',
            border: 'border-blue-600',
            hoverBorderBg: 'hover:bg-blue-100',
            textHover: 'hover:text-gray-900',
        },
        secondary: {
            bg: 'bg-purple-600',
            text: 'text-white',
            textOutline: 'text-purple-600',
            hoverBg: 'hover:bg-purple-700',
            border: 'border-purple-600',
            hoverBorderBg: 'hover:bg-purple-100',
            textHover: 'hover:text-gray-900',
        },
        tertiary: {
            bg: 'bg-gray-300',
            text: 'text-gray-700',
            textOutline: 'text-gray-700',
            hoverBg: 'hover:bg-gray-300',
            border: 'border-gray-700',
            hoverBorderBg: 'hover:bg-gray-200',
            textHover: 'hover:text-gray-900',
        },
        info: {
            bg: 'bg-cyan-500',
            text: 'text-white',
            textOutline: 'text-cyan-500',
            hoverBg: 'hover:bg-cyan-600',
            border: 'border-cyan-500',
            hoverBorderBg: 'hover:bg-cyan-100',
            textHover: 'hover:text-gray-900',
        },
        warning: {
            bg: 'bg-yellow-400',
            text: 'text-gray-900',
            textOutline: 'text-yellow-400',
            hoverBg: 'hover:bg-yellow-500',
            border: 'border-yellow-400',
            hoverBorderBg: 'hover:bg-yellow-100',
            textHover: 'hover:text-gray-900',
        },
        error: {
            bg: 'bg-red-600',
            text: 'text-white',
            textOutline: 'text-red-600',
            hoverBg: 'hover:bg-red-700',
            border: 'border-red-600',
            hoverBorderBg: 'hover:bg-red-100',
            textHover: 'hover:text-gray-900',
        },
        success: {
            bg: 'bg-green-600',
            text: 'text-white',
            textOutline: 'text-green-600',
            hoverBg: 'hover:bg-green-700',
            border: 'border-green-600',
            hoverBorderBg: 'hover:bg-green-100',
            textHover: 'hover:text-gray-900',
        },
    },
    dark: {
        primary: {
            bg: 'bg-blue-500',
            text: 'text-gray-900',
            textOutline: 'text-blue-500',
            hoverBg: 'hover:bg-blue-400',
            border: 'border-blue-500',
            hoverBorderBg: 'hover:bg-blue-800',
            textHover: 'hover:text-white',
        },
        secondary: {
            bg: 'bg-purple-500',
            text: 'text-gray-900',
            textOutline: 'text-purple-500',
            hoverBg: 'hover:bg-purple-400',
            border: 'border-purple-500',
            hoverBorderBg: 'hover:bg-purple-800',
            textHover: 'hover:text-white',
        },
        tertiary: {
            bg: 'bg-gray-700',
            text: 'text-gray-100',
            textOutline: 'text-gray-400',
            hoverBg: 'hover:bg-gray-600',
            border: 'border-gray-400',
            hoverBorderBg: 'hover:bg-gray-700',
            textHover: 'hover:text-gray-100',
        },
        info: {
            bg: 'bg-cyan-400',
            text: 'text-gray-900',
            textOutline: 'text-cyan-400',
            hoverBg: 'hover:bg-cyan-300',
            border: 'border-cyan-400',
            hoverBorderBg: 'hover:bg-cyan-800',
            textHover: 'hover:text-white',
        },
        warning: {
            bg: 'bg-yellow-500',
            text: 'text-gray-900',
            textOutline: 'text-yellow-500',
            hoverBg: 'hover:bg-yellow-600',
            border: 'border-yellow-500',
            hoverBorderBg: 'hover:bg-yellow-700',
            textHover: 'hover:text-white',
        },
        error: {
            bg: 'bg-red-500',
            text: 'text-gray-100',
            textOutline: 'text-red-500',
            hoverBg: 'hover:bg-red-400',
            border: 'border-red-500',
            hoverBorderBg: 'hover:bg-red-700',
            textHover: 'hover:text-white',
        },
        success: {
            bg: 'bg-green-500',
            text: 'text-gray-100',
            textOutline: 'text-green-500',
            hoverBg: 'hover:bg-green-400',
            border: 'border-green-500',
            hoverBorderBg: 'hover:bg-green-700',
            textHover: 'hover:text-white',
        },
    },
};
